# @package _global_

defaults:
  - _self_
  - data: ocr_datamodule # choose datamodule with `test_dataloader()` for evaluation
  - model: crnn
  - logger: null
  - trainer: gpu
  - paths: ocr_paths
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

model:
  weights_path: ../weights/crnn_vgg16_lstm256_baseline__2025_10_08.pth
